#tomcat
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#application.yml 配置如下：
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socks?useSSL=false
    username: root
    password: 123456